[project]
name = "recognize-speech-cron"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.2",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
