[project]
name = "summary"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.2",
    "dotenv>=0.9.9",
    "weasyprint>=67.0",
    "yandex-cloud-ml-sdk>=0.17.1",
    "ydb>=3.22.1",
]
